#!/bin/bash

# to fix
# check for requirement (awk, nginx, /etc/nginx/sites-available, /etc/nginx/sites-enabled, systemctl)
# imporve port parsing

VERSION=0.1
DEFAULT_PORT=8080
SITES_ENABLED="/etc/nginx/sites-enabled/"
SITES_AVAILABLE="/etc/nginx/sites-available/"

read -d '\n' template_text << EndOfText
server {
    listen %i;
    root %s;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EndOfText

read -d '\n' version_template << EndOfText
ngrol version: $VERSION
  -> nginx version:	%s
  -> systemd version:	%s
  -> awk version:	%s
  -> sites-available:	%s
  -> sites-enabled:	%s
EndOfText

read -d '\n' help_template << EndOfText
Usage: ngctl [COMMAND] [PATH] [PORT]
Easily manage nginx conf files

  start [PATH=.] [PORT=%i]    Starts a server with path as root. If not port is provided, will use first available port from 8080.
  add   [PATH=.] [PORT=%i]    Alias for start.
  del   [PATH]                NOT IMPLEMENTED
  ls                          List all servers, enabled and available.
  enable                      Enable a previously disabled server.
  disable                     Disable a previously enabled server.
  version                     Display version information.
EndOfText


declare -a servers_files=()
declare -i servers_idx=1
declare -a ports
declare server_port=""
declare server_root=""


ngctl_print_confs() {

	local path=$1
	local desc=$2
	servers_idx=$3
    servers_files=()

	for file in "${path}"ngctl.*; do
		if [ ! -f "${file}" ]; then
			if [ ${servers_idx} = 1 ]; then
  				echo "No files found..."
			fi
			break
		fi

        servers_files+=("${file}")
		local port=""
		local root=""
		local line=""
		readarray -t lines < <(cat "${file}")
		for line in "${lines[@]}"; do

			if [[ "${line}" =~ listen ]]; then
				port="${line##* listen* }"
				port="${port%%;}"
			fi
			if [[ "${line}" =~ root ]]; then
				root="${line##* root* }"
				root="${root%%;}"
			fi
			if [[ -n $port && -n $root ]]; then
				printf "[%i] %-48s http://localhost:%-15s (%s)\n" "$servers_idx" "${root}" "${port}" "${desc}";
				break
			fi
		done
		servers_idx=$((servers_idx+1))
	done
}


ngctl_get_conf_details() {

	local file=$1
	server_port=""
	server_root=""

	if [ ! -f "${file}" ]; then
		echo "Files not found..."
		return
	fi
	readarray -t lines < <(cat "${file}")
	for line in "${lines[@]}"; do

		# print "%s\n" "${line}"
		if [[ "$line" =~ listen ]]; then
			server_port="${line##* listen* }"
			server_port="${server_port%%;}"
			continue
		fi
		if [[ "$line" =~ root ]]; then
			server_root="${line##* root* }"
			server_root="${server_root%%;}"
			continue
		fi
		if [[ -n $server_port && -n $server_root ]]; then
			break
		fi
	done
}


ngctl_get_ports() {

	local i=1
	for file in "${SITES_ENABLED}"*; do
		if [ ! -f "${file}" ]; then
			break
		fi
		cat "${file}" | while read line; do
			if [[ "$line" =~ listen ]]; then
				port="${line##listen }"
				port="${port%%;}"
				ports[$i-1]=$port
				break
			fi
		done
		# printf "[%i] %-36s %-5s (%s)\n" "$i" "$file" "${port}" "enabled";
		let "i+=1"
	done
	for file in "${SITES_AVAILABLE}"*; do
		if [ ! -f "${file}" ]; then
			break
		fi
		cat "${file}" | while read line; do
			if [[ "$line" =~ listen ]]; then
				port="${line##listen }"
				port="${port%%;}"
				ports[$i-1]=$port
				break
			fi
		done
		# printf "[%i] %-36s %-5s (%s)\n" "$i" "$file" "${port}" "enabled";
		let "i+=1"
	done
}


ngctl_find_port_available() {

	ngctl_get_ports

	port=$DEFAULT_PORT
	while [[ " ${ports[*]} " =~ " ${port} " ]]; do
		let "port+=1"
	done
	return $port
}


case "$1" in

	"start" | "add" )
		location=$(pwd)"/"
		port=""

		# check for 2nd argument
		if ! [ -z "$2" ]; then
			# check if argument is a number
			if [[ "$2" =~ ^[0-9]+$ ]]; then
				# this is a port number
				port="$2"
			else
				# this should be a path
				if [ -d "$2" ]; then
					pushd "$2" >/dev/null 2>&1
					location=$(pwd)"/"
					popd >/dev/null 2>&1
				else
					printf "Error: location does not exist!"
					exit 1
				fi
			fi
		fi

		# check for 3rd argument
		if ! [ -z "$3" ]; then
			# check if argument is a number
			if [[ "$3" =~ ^[0-9]+$ ]]; then
				# this is a port number
				port="$3"
			else
				printf "Error: port should be a number!"
				exit 1
			fi
		fi

		fn="ngctl${location////.}"
		fn="${fn::-1}"
		pe="$SITES_ENABLED$fn"
		pa="$SITES_AVAILABLE$fn"

		if [ -z $port ] && ( [ -f $pa ] || [ -f $pe ] ); then
			printf 'Existing entry...\n'
			if [ -f $pa ]; then
				mv "$pa" "$pe"
			fi
			# todo get port from file
			while read line; do
				is_listen=$(echo $line | awk '{print $1}')
				if [[ "$is_listen" == *"listen"* ]]; then
					port=$(echo $line | awk '{print $2}')
				fi
			done < "${pe}"
		else
			if [ -n $port ]; then
				port=$(ngctl_find_port_available)
			fi
			# printf 'New entry...\n'
			printf "$template_text\n" $port "$location" > "$pe"
		fi

		$(nginx -t)
		$(nginx -s reload)
		printf "\nlocation enabled: %s\n" $location
		printf " --> http://localhost:%i/\n" $port
	;;


	"enable" )
		ngctl_print_confs "${SITES_AVAILABLE}" "disabled" 1
		read -p "Enter location number to enable: " option
		file="${servers_files[$option-1]##/*/}"
		mv "${SITES_AVAILABLE}${file}" "${SITES_ENABLED}${file}"
		nginx -s reload &>/dev/null
		ngctl_get_conf_details "${SITES_ENABLED}${file}"
		printf " -> %-36s http://localhost:%-5s (enabled)\n" "${server_root}" "${server_port}"
	;;


	"disable" )
		ngctl_print_confs "${SITES_ENABLED}" "enabled" 1
		read -p "Enter location number to disable: " option
		file="${servers_files[$option-1]##/*/}"
		mv "${SITES_ENABLED}${file}" "${SITES_AVAILABLE}${file}"
		nginx -s reload &>/dev/null
		ngctl_get_conf_details "${SITES_AVAILABLE}${file}"
		printf " -> %-36s http://localhost:%-5s (disabled)\n" "${server_root}" "${server_port}"
	;;


	"ls" )
		ngctl_print_confs "${SITES_ENABLED}" "enabled" 1
		ngctl_print_confs "${SITES_AVAILABLE}" "available" ${servers_idx}
	;;


	"status" )
		# Assumes active is line 3
		status=$(sudo systemctl status nginx.service | 
			while read line; do
				if [[ "$line" =~ Active: ]]; then
					status="${line##Active: }"
					status="${status%%(*}"
					printf "%s" "$status"
					break
				fi
			done)
		printf 'nginx.service is %s\n' $status 
	;;


	"version" )
		ngx_version=$(nginx -V 2>&1 | head --lines=1 | awk '{print $3}' | awk -F '/' '{print $2}')
		smd_version=$(systemctl --version 2>&1 | head --lines=1 | awk '{print $2}')
		awk_version=$(awk --version 2>&1 | head --lines=1 | awk '{print $2}')
		sites_enabled="not found"
		sites_available="not found"
		if [ -d $SITES_AVAILABLE ]; then
			sites_available="found"
		fi
		if [ -d $SITES_ENABLED ]; then
			sites_enabled="found"
		fi
		printf "$version_template\n" $ngx_version $smd_version $awk_version $sites_available $sites_enabled
	;;


	"help" )
		printf '%s\n\n' "$help_template"
	;;


	* )
		printf '%s\n\n' "$help_template"
	;;

esac
exit 0

